name: Run unit tests
on: push
jobs:
    php-unit-tests:
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php:
                    - 7.4
                    - 8.0
                os:
                    - ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, filter, json, libxml, mbstring, phar, simplexml, tokenizer, xml, xmlwriter
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install --prefer-dist --no-interaction

            -   name: Execute tests
                run: composer unittest-coverage

            -   name: Check test coverage
                uses: johanvanhelden/gha-clover-test-coverage-check@v1
                if: success()
                with:
                    percentage: 100
                    filename: test-results/clover-coverage.xml

            - name: Upload Unit Test Results
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: Unit Test Results (PHP ${{ matrix.php }} on ${{ matrix.os }})
                  path: test-results/phpunit-result.xml

    publish-test-results:
        name: "Publish Unit Tests Results"
        needs: php-unit-tests
        runs-on: ubuntu-latest
        if: success() || failure()
        steps:
            -   name: Download Artifacts
                uses: actions/download-artifact@v2
                with:
                    path: artifacts

            -   name: Publish Unit Test Results
                uses: EnricoMi/publish-unit-test-result-action@v1
                with:
                    files: artifacts/**/*.xml
